name: Build and Deploy
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        HUGGINGFACE_KEY_TOKEN: ${{ secrets.HUGGINGFACE_KEY }}
        BRANCH: gh-pages
        FOLDER: build
        CLEAN: true
