name: Obfuscate JavaScript code
on: push
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
        token: ${{ secrets.PAT }}
    - name: Install JavaScript Obfuscator
      run: npm install --save-dev javascript-obfuscator
    - name: Obfuscate JavaScript files
      run: npx javascript-obfuscator ./index.js --output ./index.js
    - name: Obfuscate JavaScript files again
      run: npx javascript-obfuscator ./module.js --output ./module.js
    - name: Commit files
      run: |
        git config --local user.email "test@test.com"
        git config --local user.name "Test"
        git add .
        git commit -m "Add changes"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PAT }}
        repository: syntz-dev/stella
        force: true

