name: Obfuscate JavaScript code
on: push
jobs:
  obfuscate_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from code branch
        uses: actions/checkout@v2
      - name: Install JavaScript Obfuscator
        run: npm install --save-dev javascript-obfuscator
      - name: Obfuscate JavaScript files
        run: npx javascript-obfuscator ./path-to-your-javascript-files --output ./path-to-output-obfuscated-files
      - name: Commit and push obfuscated files
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "youremail@example.com"
          git add -A
          git commit -m "Obfuscated JavaScript files"
          git push
